export const actionTypes = {
  // Fill actiontypes
  FETCH_FILM_LIST: "FETCH_FILM_LIST",
  FETCH_FILM_DETAIL: "FETCH_FILM_DETAIL",
  FETCH_BANNER_LIST: "FETCH_BANNER_LIST",

  // User actiontypes
  FETCH_USER_LIST: "FETCH_USER_LIST",
  FETCH_USER_DETAIL: "FETCH_USER_DETAIL",
  SEARCH_USER: "SEARCH_USER",

  //Authe actiontypes
  DANG_NHAP: "DANG_NHAP",
  DANG_XUAT: "DANG_XUAT",
  DANG_KY: "DANG_KY",
  SET_THONG_TIN: "SET_THONG_TIN",
  UPDATE_THONG_TIN: "UPDATE_THONG_TIN",

  //Theater actiontypes
  FETCH_HE_THONG_RAP: " FETCH_HE_THONG_RAP",
  FETCH_HE_THONG_RAP_THEO_PHIM: "  FETCH_HE_THONG_RAP_THEO_PHIM",

  //Booking actiontypes
  FETCH_BOOKING_ROOM: "FETCH_BOOKING_ROOM",
  CHOOSE_SLOT: "CHOOSE_SLOT",
};
